export const MOVIES_FETCHING = 'MOVIES_FETCHING';
export const MOVIES_FETCHED = 'MOVIES_FETCHED';
export const MOVIES_FETCH_HAS_ERROR = 'MOVIES_FETCH_HAS_ERROR';

export const MOVIE_DETAIL_FETCHING = 'MOVIE_DETAIL_FETCHING';
export const MOVIE_DETAIL_FETCHED = 'MOVIE_DETAIL_FETCHED';
export const MOVIE_DETAIL_FETCH_HAS_ERROR = 'MOVIE_DETAIL_FETCH_HAS_ERROR';

export const MOVIE_CREDITS_FETCHING = 'MOVIE_CREDITS_FETCHING';
export const MOVIE_CREDITS_FETCHED = 'MOVIE_CREDITS_FETCHED';
export const MOVIE_CREDITS_FETCH_HAS_ERROR = 'MOVIE_CREDITS_FETCH_HAS_ERROR';
