export default {
  movies: 'Movies',
  popular: 'Popular',
  upcoming: 'Upcoming',
  topRated: 'Top Rated',
  tvShows: 'TV Shows',
  people: 'People',
  more: 'More',
  login: 'Login',
  joinTmdb: 'Join TMDB',
  popularMovies: 'Popular Movies',
  upcomingMovies: 'Upcoming Movies',
  topRatedMovies: 'Top Rated Movies',
  search: 'Search',
  sort: 'Sort',
  filters: 'Filters',
  whereToWatch: 'Where to Watch',
};
